# Replacements are done before splitting the text into sentences


replacements = [
  ["‘", "'"],     # U+2018 => apostrophe
  ["’", "'"],     # U+2019 => apostrophe
  ["п. эрч.", "пирӗн эрӑччен"],
  ["п.эрч.", "пирӗн эрӑччен"],
  ["п. э.", "пирӗн эрӑччен"],
  ["п.э.", "пирӗн эрӑччен"],
  ["­c", "с"],      
  #["«", "\""],     
  #["»", "\""], 
  #[" ", " "],     # U+00A0 => whitespace
  #[" ", " "],     # U+2002 => whitespace
  #[" ", " "],     # U+202F => whitespace
  #["‑", "-"],     # U+2011 => hyphen
  #["–", "—"],     # U+2013 => U+2014
  #["―", "—"],     # U+2015 => U+2014
  #["−", "—"],     # U+2212 => U+2014
  #[" - ", " — "], # hyphen => U+2014, when between whitespaces
]

abbreviation_patterns = [
  # С. Маршак
  "[А-ЯӐӖҪӲĔ­ĂÇ­Ÿ]\\.",
  # Рака, Дж.
  "[А-ЯӐӖҪӲĔ­ĂÇ­Ÿ][а-яӑӗҫӳĕăçÿ]\\.",
  # АССР
  "[А-ЯӐӖҪӲĔ­ĂÇ­Ÿ]{2,}",
  # Мелодия п.у.
  "[а-яәҗңөүһĕăçÿ]\\.[А-ЯӘҖҢӨҮҺа-яәҗңөүһĔ­ĂÇ­Ÿĕăçÿ]",
  # т. с. Тиккĕ
  "\\s[а-яәҗңөүһĕăçÿ]\\.",
  # пр.-тюркск.
  "\\.\\-",
  # \s[А-ЯӐӖҪӲа-яӑӗҫӳ]{2}\.
  #\s(?!пĕри|тăнă|йытӑ|тӑнӑ|хунă|пӗри|кĕне).{4}\.
  "[^А-ЯӐӖҪӲа-яӑӗҫӳĕăçÿĔ­ĂÇ­Ÿ](—|лат|км|ур|им|зам|ыт|тв|тс|яч|ул|чăв|реж|хис|укр|паç|Ниж|вып|сăв|инв|Сăв)\\.$",
  # Наци б-ки.
  "[а-яӑӗҫӳĕăçÿ]{1,2}\\-[а-яӑӗҫӳĕăçÿ]{1,4}",
]


# 
# 
# 

min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 2
may_end_with_colon = true
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = true
allowed_symbols_regex = "[А-ЯӐӖҪӲа-яӑӗҫӳ'\\s,.\\-‑?!—­‐–―−„“\"«»ĕăçÿĔ­ĂÇ­Ÿ]"
#disallowed_symbols = ['(', ')']
#disallowed_symbols = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 
#'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z',
# '<', '>', '+', '*']
broken_whitespace =  ["  ", " ,", " .", " ?", " !", " ;"]
matching_symbols = [
  ["„", "“"],
  ["(", ")"],
  ["«", "»"],
]

other_patterns = [
    # Some Russian stopwords not present in Tatar language
    # не, в, на, с, что, к, по, у, из, был, то, которого, весь, и
    #"(\\s?\\s^[не|в|на|с|что|к|по|у|из|был|то|которого|весь|и|это])"
    #"(\\sне\\s|\\sВ\\s|\\sв\\s|\\sна\\s|\\sс\\s|\\sчто\\s|\\sк\\s|\\sпо\\s|\\sу\\s|\\sиз\\s|\\sбыл\\s|\\sто\\s|\\sкоторого\\s|\\sвесь\\s|\\sи\\s|\\sэто\\s)",
    "(\\sна\\s|\\sне\\s|\\sиз\\s|\\sв\\s|\\sВот\\s)",
    "(юханшыва юхса кĕрет|хулинче вырнаçнă|территорипе юхать)"
    # City was found in this year
    #"[MCLXVI]\\s",
    # russianWords = [ 
    #            ' быть ',' я ',' он ',' а ', 
    #            ' это ',' так ',' то ',' этот ', 
    #            ' они ',' мы ',' но ', 
    #            ' она ',' который ', 
    #            ' вы ',' так ', ' в ']
]


