# Replacements are done before splitting the text into sentences


replacements = [
  ["a", "а"],
  ["A", "А"],  
  ["c", "с"],
  ["C", "С"],
  ["e", "е"],
  ["E", "Е"],
  ["h", "һ"],
  ["H", "Н"],
  ["o", "о"],
  ["O", "О"],
  ["p", "р"],
  ["P", "Р"],
  ["x", "х"],
  ["X", "Х"],
  #["һ.б.", "һәм башкалар"],
  #["Һ.б.", "һәм башкалар"],
  #["һ.б", "һәм башкалар"],
  #["һ. б.", "һәм башкалар"],
  #["б.э.к.", "безнең эрага кадәр"],
  #["б. э. к.", "безнең эрага кадәр"],
  #["б. э.к.", "безнең эрага кадәр"],
  #["б.э.", "безнең эрага"],
  #["б. э.", "безнең эрага"],
  #[", мәс.", ", мәсәлән"],
  #["а.х.", "авыл хуҗалыгының"],
  #[" ис.", " исемендәге"],
  #[" ур.", " урамы"],
  #["б. ш.", "башка шундыйлар"],
  #["ш.о", "шәһәр округы"],
  #["ш.т.б", "шәһәр тибындагы бистә"],
  #[" ш.", " шәһәре"],
  #[" а.", " авылы"],
  #["‘", "'"],     # U+2018 => apostrophe
  #["’", "'"],     # U+2019 => apostrophe
  #["«", "\""],     
  #["»", "\""],  
  #["­", ""],       # U+00AD => empty string
  #[" ", " "],     # U+00A0 => whitespace
  #[" ", " "],     # U+2002 => whitespace
  #[" ", " "],     # U+202F => whitespace
  #["‑", "-"],     # U+2011 => hyphen
  #["–", "—"],     # U+2013 => U+2014
  #["―", "—"],     # U+2015 => U+2014
  #["−", "—"],     # U+2212 => U+2014
  #[" - ", " — "], # hyphen => U+2014, when between whitespaces
]
abbreviation_patterns = [
  # С.М.Ахинжанов
  "[А-ЯҔҊҤӨҺҮ]\\.",
  # Дж.
  "[А-ЯҔҊҤӨҺҮ][а-яҕҋҥөһү]\\.",
  # Элбэх ССРС
  "[А-ЯҔҊҤӨҺҮ]{2,}",
  # үүнээйи.Сэбирдэхтэрэ
  "[а-яҕҋҥөһү]\\.[А-ЯҔҊҤӨҺҮа-яҕҋҥөһү]",
  # о. д. а.
  "\\s[а-яҕҋҥөһү]\\.",
  # А.-З
  "\\.\\-",
  # 
  "[^А-ЯҔҊҤӨҺҮа-яҕҋҥөһү](аат|дат|Нац|пед|ред|соц|таб|монг|Респ||азерб)\\.$",
]

#19925
#18077
#13355

min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 2
may_end_with_colon = true
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = true
allowed_symbols_regex = "[А-ЯҔҊҤӨҺҮа-яҕҋҥөһү'\\s,.\\-‑?!—­‐–―−„“\"«»]"
broken_whitespace =  ["  ", " ,", " .", " ?", " !", " ;"]
matching_symbols = [
  ["„", "“"],
  ["(", ")"],
  ["«", "»"],
  ["\"", "\""],
]

other_patterns = [
    # Some Russian stopwords not present in Tatar language
    # не, в, на, с, что, к, по, у, из, был, то, которого, весь, и
    #"(\\s?\\s^[не|в|на|с|что|к|по|у|из|был|то|которого|весь|и|это])"
    "(\\sпочти\\s|\\sне\\s|\\sВ\\s|\\sв\\s|\\sна\\s|\\sс\\s|\\sчто\\s|\\sк\\s|\\sпо\\s|\\sу\\s|\\sиз\\s|\\sбыл\\s|\\sто\\s|\\sкоторого\\s|\\sвесь\\s|\\sи\\s|\\sэто\\s)",
    # City was found in this year
    "(нэһилиэгэ, киинэ|Национальная|день|вчера|Якутии|край|люди|труд|узел|ский|ская)",
    # russianWords = [ 
    #            ' быть ',' я ',' он ',' а ', 
    #            ' это ',' так ',' то ',' этот ', 
    #            ' они ',' мы ',' но ', 
    #            ' она ',' который ', 
    #            ' вы ',' так ', ' в ']
    
  
]


