# Replacements are done before splitting the text into sentences


replacements = [
  ["һ.б.", "һәм башкалар"],
  ["Һ.б.", "һәм башкалар"],
  ["һ.б", "һәм башкалар"],
  ["һ. б.", "һәм башкалар"],
  ["б.э.к.", "безнең эрага кадәр"],
  ["б. э. к.", "безнең эрага кадәр"],
  ["б. э.к.", "безнең эрага кадәр"],
  ["б.э.", "безнең эрага"],
  ["б. э.", "безнең эрага"],
  [", мәс.", ", мәсәлән"],
  ["а.х.", "авыл хуҗалыгының"],
  [" ис.", " исемендәге"],
  [" ур.", " урамы"],
  ["б. ш.", "башка шундыйлар"],
  ["ш.о", "шәһәр округы"],
  ["ш.т.б", "шәһәр тибындагы бистә"],
  #[" ш.", " шәһәре"],
  #[" а.", " авылы"],
  ["a", "а"],
  ["A", "А"],  
  ["c", "с"],
  ["C", "С"],
  ["e", "е"],
  ["E", "Е"],
  ["h", "һ"],
  ["H", "Н"],
  ["o", "о"],
  ["O", "О"],
  ["p", "р"],
  ["P", "Р"],
  ["x", "х"],
  ["X", "Х"],
  #["", "'"],
  #["‘", "'"],     # U+2018 => apostrophe
  #["’", "'"],     # U+2019 => apostrophe
  #["«", "\""],     
  #["»", "\""],  
]
abbreviation_patterns = [
  # А.Гыйләҗев
  "[А-ЯӘҖҢӨҮҺ]\\.",
  # Дж.
  "[А-ЯӘҖҢӨҮҺ][а-яәҗңөүһ]\\.",
  # ССРБ
  "[А-ЯӘҖҢӨҮҺ]{2,}",
  # Эшмәкәрләр и.с.
  "[а-яәҗңөүһ]\\.[А-ЯӘҖҢӨҮҺа-яәҗңөүһ]",
  # Йөзләрчә а.б.
  "\\s[а-яәҗңөүһ]\\.",
  # пр.-тюркск.
  "\\.\\-",
  # 
  #\s(?!пĕри|тăнă|йытӑ|тӑнӑ|хунă|пӗри|кĕне).{4}\.
  "[^А-ЯӘҖҢӨҮҺа-яәҗңөүһ](әд|оз|св|ст|гос|губ|дис|Евг|җәд|лаб|лат|муз|общ|нар|орд|ред|англ|Верх|коэф|метр|макс|Прав|башк)\\.$",
  
]


min_trimmed_length = 3
min_word_count = 2
max_word_count = 15
min_characters = 2
may_end_with_colon = true
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = true
allowed_symbols_regex = "[А-ЯӘҖҢӨҮҺа-яәҗңөүһ'\\s,.\\-‑?!—­‐–―−„“\"«»]"
broken_whitespace =  ["  ", " ,", " .", " ?", " !", " ;"]
matching_symbols = [
  ["„", "“"],
  ["(", ")"],
  ["«", "»"],
]

#71962  3=max-freq
#70051  4=max_freq 68559 62639 62779 60739

other_patterns = [
    # Some Russian stopwords not present in Tatar language
    # не, в, на, с, что, к, по, у, из, был, то, которого, весь, и
    #"(\\s?\\s^[не|в|на|с|что|к|по|у|из|был|то|которого|весь|и|это])"
    "(\\sне\\s|\\sв\\s|\\sна\\s|\\sс\\s|\\sчто\\s|\\sк\\s|\\sпо\\s|\\sу\\s|\\sиз\\s|\\sбыл\\s|\\sто\\s|\\sкоторого\\s|\\sвесь\\s|\\sи\\s|\\sэто\\s)",
    # City was found in this year
    "(шәһәре елда нигезләнгән|климаты уртача-континенталь|биләмәләрендә ага|аның кушылдыгы булып тора)",
    #
    # russianWords = [ 
    #            ' быть ',' я ',' он ',' а ', 
    #            ' это ',' так ',' то ',' этот ', 
    #            ' они ',' мы ',' но ', 
    #            ' она ',' который ', 
    #            ' вы ',' так ', ' в ']
    "(ться|тся|конечно|учебных|научных|животных)",
    "(км|әммә)"
    # 49371
    # 37032
    # 37786
    # Тетис йортлар-коттеджлардан  Велс вәйран Ун өч шөгелләнергә  әммә
    # предприятеләре юнәлеше-массакүләм км Журналистар
    # сож предприятеләре
]


